name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up Tools
        run: |
          go get -u github.com/fzipp/gocyclo
          go get -u github.com/mattn/goveralls
          go get -u golang.org/x/lint/golint

      - name: Test
        run: make test

      - name: Test for Race Conditions
        run: make test-race

      - name: Benchmark
        run: make bench

      - name: Upload Coverage Report
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: $GOPATH/bin/goveralls -service=travis-pro -coverprofile=.coverprofile
